from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class AuditEventType(StrEnum):
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    DOCUMENT_PARSED = "DOCUMENT_PARSED"

    LLM_CALL_STARTED = "LLM_CALL_STARTED"
    LLM_CALL_COMPLETED = "LLM_CALL_COMPLETED"
    LLM_CALL_FAILED = "LLM_CALL_FAILED"

    SCHEMA_VALIDATION_COMPLETED = "SCHEMA_VALIDATION_COMPLETED"
    SEMANTIC_VALIDATION_COMPLETED = "SEMANTIC_VALIDATION_COMPLETED"
    HUMAN_REVIEW_RECORDED = "HUMAN_REVIEW_RECORDED"

    RULE_LOADED = "RULE_LOADED"
    DATE_EXPRESSION_RESOLVED = "DATE_EXPRESSION_RESOLVED"

    FACT_REQUESTED = "FACT_REQUESTED"
    FACT_CANDIDATES_FOUND = "FACT_CANDIDATES_FOUND"
    FACT_SOURCE_SELECTED = "FACT_SOURCE_SELECTED"
    FACT_CONFLICT_DETECTED = "FACT_CONFLICT_DETECTED"
    SERVICE_RESOLVER_CALLED = "SERVICE_RESOLVER_CALLED"

    DATA_COVERAGE_CHECKED = "DATA_COVERAGE_CHECKED"
    AGGREGATION_EXECUTED = "AGGREGATION_EXECUTED"
    COMPARISON_EXECUTED = "COMPARISON_EXECUTED"
    FUTURE_CAPACITY_CHECKED = "FUTURE_CAPACITY_CHECKED"

    MISSING_FACT_CREATED = "MISSING_FACT_CREATED"
    USER_FACT_RECEIVED = "USER_FACT_RECEIVED"

    STATUS_DERIVED = "STATUS_DERIVED"
    REWARD_APPLIED = "REWARD_APPLIED"
    RATE_SUMMARY_CREATED = "RATE_SUMMARY_CREATED"

    GOAL_CREATED = "GOAL_CREATED"
    GOAL_PROGRESS_UPDATED = "GOAL_PROGRESS_UPDATED"
    GOAL_FEASIBILITY_RECALCULATED = "GOAL_FEASIBILITY_RECALCULATED"

    ALERT_TRIGGERED = "ALERT_TRIGGERED"
    RESULT_EXPLAINED = "RESULT_EXPLAINED"

    SEARCH_SESSION_CREATED = "SEARCH_SESSION_CREATED"
    SEARCH_INTENT_PARSED = "SEARCH_INTENT_PARSED"
    SEARCH_INTENT_UPDATED = "SEARCH_INTENT_UPDATED"
    INTENT_CONFLICT_DETECTED = "INTENT_CONFLICT_DETECTED"
    CLARIFICATION_REQUESTED = "CLARIFICATION_REQUESTED"
    CLARIFICATION_RESOLVED = "CLARIFICATION_RESOLVED"
    CANDIDATE_FILTERED = "CANDIDATE_FILTERED"
    CANDIDATE_RETAINED = "CANDIDATE_RETAINED"
    CANDIDATE_EVALUATED = "CANDIDATE_EVALUATED"
    OPTIMISTIC_BOUND_CALCULATED = "OPTIMISTIC_BOUND_CALCULATED"
    QUESTION_CANDIDATE_SCORED = "QUESTION_CANDIDATE_SCORED"
    QUESTION_SELECTED = "QUESTION_SELECTED"
    USER_ANSWER_SUPERSEDED = "USER_ANSWER_SUPERSEDED"
    USER_DECLARED_FACT_SUPERSEDED_BY_INTENT_UPDATE = "USER_DECLARED_FACT_SUPERSEDED_BY_INTENT_UPDATE"
    PRODUCT_CONTRIBUTION_INPUT_REQUESTED = "PRODUCT_CONTRIBUTION_INPUT_REQUESTED"
    PRODUCT_CONTRIBUTION_INPUT_RECORDED = "PRODUCT_CONTRIBUTION_INPUT_RECORDED"
    CONTRIBUTION_OPTION_FEASIBILITY_EVALUATED = "CONTRIBUTION_OPTION_FEASIBILITY_EVALUATED"
    CONTRIBUTION_OPTION_PRUNED = "CONTRIBUTION_OPTION_PRUNED"
    CONTRIBUTION_FEASIBILITY_CLARIFICATION_CREATED = "CONTRIBUTION_FEASIBILITY_CLARIFICATION_CREATED"
    CONTRIBUTION_ANSWER_REJECTED = "CONTRIBUTION_ANSWER_REJECTED"
    PRODUCT_EXCLUDED_BY_USER = "PRODUCT_EXCLUDED_BY_USER"
    GLOBAL_AFFORDABILITY_UPDATED = "GLOBAL_AFFORDABILITY_UPDATED"
    USER_STATE_REVISION_REQUESTED = "USER_STATE_REVISION_REQUESTED"
    CONVERSATION_TURN_RECEIVED = "CONVERSATION_TURN_RECEIVED"
    MUTABLE_SEARCH_STATE_UPDATED = "MUTABLE_SEARCH_STATE_UPDATED"
    CONVERSATION_TURN_ROLLED_BACK = "CONVERSATION_TURN_ROLLED_BACK"
    PRODUCT_CONTRIBUTION_CHOICE_SUPERSEDED = "PRODUCT_CONTRIBUTION_CHOICE_SUPERSEDED"
    PRODUCT_CHOICE_UPDATED = "PRODUCT_CHOICE_UPDATED"
    PRODUCT_EXCLUSION_CHANGED = "PRODUCT_EXCLUSION_CHANGED"
    DEPENDENCY_INVALIDATED = "DEPENDENCY_INVALIDATED"
    QUESTION_REOPENED = "QUESTION_REOPENED"
    AUTHORITATIVE_REVISION_REJECTED = "AUTHORITATIVE_REVISION_REJECTED"
    SEARCH_RECALCULATED = "SEARCH_RECALCULATED"
    MUTABLE_VALUE_CLEARED = "MUTABLE_VALUE_CLEARED"
    CURRENT_RESULTS_REQUESTED = "CURRENT_RESULTS_REQUESTED"
    WORKING_NOTE_CREATED = "WORKING_NOTE_CREATED"
    WORKING_NOTE_UPDATED = "WORKING_NOTE_UPDATED"
    WORKING_NOTE_REBUILT = "WORKING_NOTE_REBUILT"
    WORKING_NOTE_DELETED = "WORKING_NOTE_DELETED"
    WORKING_NOTE_WRITE_FAILED = "WORKING_NOTE_WRITE_FAILED"
    RANKING_CALCULATED = "RANKING_CALCULATED"
    TOP_K_STABILITY_CHECKED = "TOP_K_STABILITY_CHECKED"
    RECOMMENDATION_CREATED = "RECOMMENDATION_CREATED"
    PRODUCT_DETAIL_OPENED = "PRODUCT_DETAIL_OPENED"
    EXPLANATION_GENERATED = "EXPLANATION_GENERATED"

    ELIGIBILITY_TEXT_REVIEW_REQUESTED = "ELIGIBILITY_TEXT_REVIEW_REQUESTED"
    ELIGIBILITY_TEXT_REVIEW_COMPLETED = "ELIGIBILITY_TEXT_REVIEW_COMPLETED"
    ELIGIBILITY_TEXT_REVIEW_REJECTED = "ELIGIBILITY_TEXT_REVIEW_REJECTED"
    ELIGIBILITY_TEXT_REVIEW_INVALIDATED = "ELIGIBILITY_TEXT_REVIEW_INVALIDATED"
    ELIGIBILITY_TEXT_REVIEW_APPLIED = "ELIGIBILITY_TEXT_REVIEW_APPLIED"
    ELIGIBILITY_REVIEW_FRONTIER_CHANGED = "ELIGIBILITY_REVIEW_FRONTIER_CHANGED"


class LLMPayloadMode(StrEnum):
    NONE = "NONE"
    HASHED = "HASHED"
    REDACTED = "REDACTED"
    FULL_DEBUG = "FULL_DEBUG"


class AuditEvent(BaseModel):
    """Immutable append-only event persisted by an :class:`AuditSink`."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    event_id: str
    occurred_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    request_id: str
    evaluation_id: str | None = None
    trace_id: str

    search_session_id: str | None = None
    intent_version: int | None = None
    ranking_run_id: str | None = None
    question_id: str | None = None
    recommendation_id: str | None = None

    span_id: str | None = None
    parent_span_id: str | None = None

    component: str
    event_type: AuditEventType

    entity_refs: dict[str, str] = Field(default_factory=dict)

    input_hash: str | None = None
    output_hash: str | None = None

    payload: dict[str, Any] = Field(default_factory=dict)
    provenance: list[dict[str, Any]] = Field(default_factory=list)
